### ISSUE TITLE
Action which requires Voice Match

### ISSUE THREAD

**Issue by stephanlarsson** [tronikos/google_assistant_sdk_custom#15]
Hi want to create an automation from which I get a response from google assistant telling me to authenticate using voice match. Is there a way to prerecord my request and play it back to the google assistant sdk custom to trigger my command?

**Comment by tronikos** [comment]
Added a note in the underlying library "Commands that need to verify your identity through voice match don't work"

The service allows passing audio instead of text but the underlying library doesn't allow that. Not sure if passing your voice recording would satisfy voice match. I'm afraid not since I think the voice match is done via the hot word and the service doesn't allow passing hot word. If you want you can try one of the samples in https://github.com/googlesamples/assistant-sdk-python/tree/master/google-assistant-sdk/googlesamples/assistant/grpc The underlying library is based on the textinput.py. I think you t want to try pushtotalk.py
