### ISSUE TITLE
No longer loading after most recent HA update

### ISSUE THREAD

**Issue by billytkid** [tronikos/google_assistant_sdk_custom#4]
This error originated from a custom integration.

Logger: custom_components.google_assistant_sdk_custom
Source: custom_components/google_assistant_sdk_custom/__init__.py:33
Integration: Google Assistant SDK Custom (documentation, issues)
First occurred: 21:12:35 (2 occurrences)
Last logged: 21:34:34

Failed to apply patch :(

-------------

This error originated from a custom integration.

Logger: custom_components.google_assistant_sdk_custom
Source: custom_components/google_assistant_sdk_custom/__init__.py:27
Integration: Google Assistant SDK Custom (documentation, issues)
First occurred: 21:12:35 (2 occurrences)
Last logged: 21:34:34

Error running command: git apply -p4 -- /config/custom_components/google_assistant_sdk_custom/google_assistant_sdk.patch - stderr:b'error: patch failed: __init__.py:2\nerror: __init__.py: patch does not apply\nerror: patch failed: helpers.py:2\nerror: helpers.py: patch does not apply\nerror: helpers2.py: already exists in working directory\n', stdout:b''

-----------

any ideas?

**Comment by tronikos** [comment]
What's your installation method of Home Assistant?

**Comment by billytkid** [comment]
Installed via HACS, running on the HAVM. Supported setup and healthy
Thx

**Comment by tronikos** [comment]
HAVM? What does it stand for?

I've been using Home Assistant Operating System that is using docker. After every HA update the docker image is redownloaded and any patches, added and modified files, are lost. I think if you are using the core installation a HA update will only reset modified files and not remove added files. That's why helpers2.py is left behind and this custom integration cannot tell if the patch has been applied or not.

If that's the case, I don't have the time to support the core installation. Feel free to send me a PR to merge.

**Comment by billytkid** [comment]
Sorry, I meant the HA standard VM = Home Assistant Operating System. 

I'm not quite following, are you saying HAOS is supported and should work, or it should not?

**Comment by tronikos** [comment]
HAOS is supported and should work it updates.

Did you recently upgrade this integration? There was a breaking change see https://github.com/tronikos/google_assistant_sdk_custom/releases/tag/v0.0.3

You will have to downgrade, delete the integration, update and install it again. Alternatively, you can update Home Assistant to a newer version, since updating Home Assistant resets all files.

**Comment by tronikos** [comment]
I assume you were able to resolve this. If not, please reopen.
